from __future__ import annotations

from lineage_guard.models import GuardResult

MARKER = "<!-- proactive-zero-ops-lineage-guard -->"


def _safe(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ").strip()


def render_markdown(result: GuardResult) -> str:
    icon = {"pass": "✅", "warn": "⚠️", "block": "⛔", "error": "❌"}[result.status]
    lines = [
        MARKER,
        "## Downstream impact assessment",
        "",
        (
            f"{icon} **{result.status.upper()}** — severity `{result.severity.value}`, "
            f"confidence `{result.confidence:.2f}`"
        ),
        "",
        _safe(result.summary),
    ]

    if result.changed_columns:
        lines.extend(
            [
                "",
                "### Changed contracts",
                "",
                "| Dataset | Column | Before | After |",
                "| --- | --- | --- | --- |",
            ]
        )
        for change in result.changed_columns:
            lines.append(
                f"| `{_safe(change.table)}` | `{_safe(change.column)}` | "
                f"{_safe(change.old_contract)} | {_safe(change.new_contract)} |"
            )

    if result.impacts:
        lines.extend(["", "### Grounded downstream impacts", ""])
        for impact in result.impacts:
            path = " → ".join(f"`{_safe(table)}`" for table in impact.path)
            lines.extend(
                [
                    f"- **{_safe(impact.asset)}** — {_safe(impact.failure_mode)}",
                    f"  - Path: {path}",
                    f"  - Evidence: {_safe(impact.evidence)}",
                ]
            )

    if result.warnings:
        lines.extend(["", "### Warnings", ""])
        lines.extend(f"- {_safe(warning)}" for warning in result.warnings)

    if result.error:
        lines.extend(["", "### Checker error", "", f"`{_safe(result.error)}`"])

    lines.extend(
        [
            "",
            f"Observed `{len(result.lineage_edges)}` deduplicated lineage edges.",
            "",
            (
                "_Generated by the trusted base-branch lineage guard; pull-request code was not "
                "executed._"
            ),
        ]
    )
    return "\n".join(lines) + "\n"
