// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import '@databricks/appkit-ui/react';
import type {
  SQLTypeMarker,
  SQLStringMarker,
  SQLNumberMarker,
  SQLBooleanMarker,
  SQLBinaryMarker,
  SQLDateMarker,
  SQLTimestampMarker,
} from '@databricks/appkit-ui/js';

declare module '@databricks/appkit-ui/react' {
  interface QueryRegistry {
    asset_access: {
      name: 'asset_access';
      parameters: {
        /** STRING - use sql.string() */
        assets_json: SQLStringMarker;
      };
      result: Array<{
        /** @sqlType INT */
        ordinal: number;
        /** @sqlType STRING */
        asset_reference: string;
        /** @sqlType BOOLEAN */
        can_select: boolean;
        /** @sqlType STRING */
        asset_type: string;
      }>;
    };
  }
}
