// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import '@databricks/appkit-ui/react';
import type {
  SQLTypeMarker,
  SQLStringMarker,
  SQLNumberMarker,
  SQLBooleanMarker,
  SQLBinaryMarker,
  SQLDateMarker,
  SQLTimestampMarker,
} from '@databricks/appkit-ui/js';

declare module '@databricks/appkit-ui/react' {
  interface QueryRegistry {
    dataset_sample: {
      name: 'dataset_sample';
      parameters: {
        /** STRING - use sql.string() */
        asset_reference: SQLStringMarker;
        /** INT - use sql.int() */
        sample_limit: SQLNumberMarker;
      };
      result: Array<{
        /** @sqlType STRING */
        row_json: string;
        /** @sqlType STRING */
        row_type: string;
      }>;
    };
  }
}
